version: '2'
services:
    tjing-app:
        image: tjing
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://tjing-postgresql:5432/tjing
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    tjing-postgresql:
        extends:
            file: postgresql.yml
            service: tjing-postgresql
